CREATE TABLE IF NOT EXISTS event_activity_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 occurred_at TIMESTAMP(6) NOT NULL, event_id BIGINT NOT NULL,
 actor_id BIGINT, subject_id BIGINT, mate_post_id BIGINT NOT NULL,
 activity_type VARCHAR(40) NOT NULL, score_delta INT NOT NULL,
 source_type VARCHAR(30) NOT NULL, source_id BIGINT NOT NULL,
 idempotency_key VARCHAR(100) NOT NULL, payload VARCHAR(1000), created_at TIMESTAMP(6) NOT NULL,
 UNIQUE(idempotency_key, occurred_at)
);
DELETE FROM event_activity_logs;
